export const refs = {
  categoriesList: document.querySelector('.categories'),
  productsList: document.querySelector('.products'),
  loadMoreBtn: document.querySelector('.load-more'),
  searchForm: document.querySelector('.search-form'),
  searchInput: document.querySelector('.search-form input'),
  clearSearchBtn: document.querySelector('.search-form__btn-clear'),
  modal: document.querySelector('.modal'),
  modalContent: document.querySelector('.modal-product'),
  modalCloseBtn: document.querySelector('.modal__close-btn'),
  backdrop: document.querySelector('.modal'),
  wishlistCount: document.querySelector('[data-count="wishlist"]'),
  cartCount: document.querySelector('[data-count="cart"]'),
  scrollUpBtn: document.querySelector('.scroll-up'),
  themeBtn: document.querySelector('.theme-toggle'),
  cartItemsCount: document.querySelector('[data-cart-items]'),
  cartTotalPrice: document.querySelector('[data-cart-total]'),
  buyBtn: document.querySelector('.cart-summary__btn'),
};